# Generated by Django 4.2.1 on 2023-06-15 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Resoults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('faceDir', models.CharField(max_length=50)),
                ('voiceDir', models.CharField(max_length=50)),
                ('faceClass', models.CharField(max_length=10)),
                ('voiceClass', models.CharField(max_length=10)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('result', models.TextField()),
            ],
        ),
    ]
